spring:
  datasource:
    url: jdbc:mysql://localhost:3306/develhopejpa
    username: root
    password: A1991a++
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    database : mysql
    show-database : true

    hibernate:
      ddl-auto: create-drop
